# @package _global_
name: stack
gpu: 0
dataset:
  name: example
  token:
    max_parts: 50
    is_wrapped: false
    is_splitted: false
    vocabulary_size: 190000

classifier:
  n_hidden_layers: 2
  hidden_size: 16

hyper_parameters:
  vector_length: 50
  seq_len: 50
  n_epochs: 50
  patience: 50
  learning_rate: 0.01
  weight_decay: 0
  decay_gamma: 0.95
  batch_size: 64
  test_batch_size: 64
  reload_dataloader: true
  clip_norm: 0
  random_context: true
  shuffle_data: true
  log_interval: 1
  optimizer: "Adam"
  nesterov: true

cl:
  n_epochs: 50
  cv_n_folds: 5
  batch_size: 64
  thresholds: 0.7